package model;

public class Application {
    private int applicationId;
    private int adopterId;
    private int petId;
    private String status; // e.g., "pending", "approved", "rejected"
    private String address;
    private String mobileNumber;
    private String notes;

    // Constructor for creating new applications (ID generated by DB)
    public Application(int adopterId, int petId) {
        this(0, adopterId, petId, "pending", "", "", ""); // Default status and empty fields
    }

    // Constructor for retrieving from DB
    public Application(int applicationId, int adopterId, int petId, String status, String address, String mobileNumber, String notes) {
        this.applicationId = applicationId;
        this.adopterId = adopterId;
        this.petId = petId;
        this.status = status;
        this.address = address;
        this.mobileNumber = mobileNumber;
        this.notes = notes;
    }

    // Getters
    public int getApplicationId() { return applicationId; }
    public int getAdopterId() { return adopterId; }
    public int getPetId() { return petId; }
    public String getStatus() { return status; }
    public String getAddress() { return address; }
    public String getMobileNumber() { return mobileNumber; }
    public String getNotes() { return notes; }

    // Setters
    public void setApplicationId(int applicationId) { this.applicationId = applicationId; }
    public void setAdopterId(int adopterId) { this.adopterId = adopterId; }
    public void setPetId(int petId) { this.petId = petId; }
    public void setStatus(String status) { this.status = status; }
    public void setAddress(String address) { this.address = address; }
    public void setMobileNumber(String mobileNumber) { this.mobileNumber = mobileNumber; }
    public void setNotes(String notes) { this.notes = notes; }

    @Override
    public String toString() {
        return "Application #" + applicationId + " [AdopterID: " + adopterId + ", PetID: " + petId + 
               ", Status: " + status + ", Address: " + address + ", Mobile: " + mobileNumber + "]";
    }
}