package model;

public class Application {
    private int applicationId;
    private int adopterId;
    private int petId;
    private String status; // e.g., "pending", "approved", "rejected"

    // Constructor for creating new applications (ID generated by DB)
    public Application(int adopterId, int petId) {
        this(0, adopterId, petId, "pending"); // Default status
    }

    // Constructor for retrieving from DB
    public Application(int applicationId, int adopterId, int petId, String status) {
        this.applicationId = applicationId;
        this.adopterId = adopterId;
        this.petId = petId;
        this.status = status;
    }

    // Getters
    public int getApplicationId() { return applicationId; }
    public int getAdopterId() { return adopterId; }
    public int getPetId() { return petId; }
    public String getStatus() { return status; }

    // Setters (mainly for status update)
    public void setApplicationId(int applicationId) { this.applicationId = applicationId; }
    public void setAdopterId(int adopterId) { this.adopterId = adopterId; }
    public void setPetId(int petId) { this.petId = petId; }
    public void setStatus(String status) { this.status = status; }

    @Override
    public String toString() {
        return "Application #" + applicationId + " [AdopterID: " + adopterId + ", PetID: " + petId + ", Status: " + status + "]";
    }
}